AWSTemplateFormatVersion: 2010-09-09

Description: Template of ALB for Lecture10

#-----------------------------------------------------------------------------------------------
Parameters:
# Naming Rule of Parameters: Property name(defined in Resources) + Resource Type (+ other identifiers)
# Other identifiers mean Resource Type in parent layer, ID-number etc. for example
#-----------------------------------------------------------------------------------------------
  EnvironmentName:
    Description: Added to a Value of a Name(Key) in Resource's Tag. EnvironmentName must be the same in templates for Cross Stack
    Type: String
    Default: lecture10

#-----------------------------------------------------------------------------------------------
Resources:
# Naming Rule of logical IDs: EnvironmentName + Resource Type (+ other identifiers)
# Naming Rule of Tags Name's Value: EnvironmentName (+ other identifiers) + Resource Type(abbreviations)
#-----------------------------------------------------------------------------------------------
  Lecture10LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: false  #default
        - Key: idle_timeout.timeout_seconds
          Value: 60  #default
        - Key: routing.http.desync_mitigation_mode
          Value: defensive  #default (monitor | defensive | strictest)
      Name: !Sub ${EnvironmentName}-lb # must be unique per region per account, can have a maximum of 32 characters(only alphanumeric characters or hyphens)
      Scheme: internet-facing  #default (internet-facing | internal)
      SecurityGroups:
        - Fn::ImportValue:
            !Sub ${EnvironmentName}-security-group-alb
      Subnets:  #Must specify either Subnets or SubnetMappings, but not both
        - Fn::ImportValue:
            !Sub ${EnvironmentName}-subnet-public1
        - Fn::ImportValue:
            !Sub ${EnvironmentName}-subnet-public2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-lb
      Type: application  #default (application | network | gateway)

  Lecture10TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      IpAddressType: ipv4
      Matcher:
        HttpCode: 200
      Name: !Sub ${EnvironmentName}-tg
      Port: 80
      Protocol: HTTP
      ProtocolVersion: HTTP1
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-tg
      Targets:
        - Id:
            Fn::ImportValue:
              !Sub ${EnvironmentName}-instance-ec2 #If the target type of the target group is instance, specify an instance ID.
      TargetType: instance #default (instance | ip | lambda | alb)
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue:
          !Sub ${EnvironmentName}-vpc

  Lecture10Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref Lecture10TargetGroup
          Type: forward  #(forward | authenticate-oidc | authenticate-cognito | redirect | fixed-response)
      LoadBalancerArn: !Ref Lecture10LoadBalancer
      Port: 80
      Protocol: HTTP  #(HTTP | HTTPS | TCP | TLS | UDP | TCP_UDP | GENEVE)

#-----------------------------------------------------------------------------------------------
Outputs:
# Naming Rule of Export Name : EnvironmentName(defined in parameters) + Resource Type (+ other identifiers)
# Without abbreviations such as rt(route table), except for AWS's service name such as VPC
#-----------------------------------------------------------------------------------------------
  OutputLecture10LoadBalancer:
    Description: Application Load Balancer ARN
    Value: !GetAtt Lecture10LoadBalancer.LoadBalancerArn
    Export:
      Name: !Sub ${EnvironmentName}-load-balancer

  OutputLecture10TargetGroup:
    Description: Target Group ARN
    Value: !GetAtt Lecture10TargetGroup.TargetGroupArn
    Export:
      Name: !Sub ${EnvironmentName}-target-group
